<?php include('header.php'); ?>


<section class="">
<img style="margin-bottom:15px;" src="img/Main-Hero-Banner1.jpg" width="100%" alt="kfc franchise">

</section>
<h1 class="titletnc">OUR BLOG</h1>
<div class="tempblog">
<div class="container">
<div class="row">
<p><b>Franchise Description:</b> The franchisor is KFC US, LLC (KFCLLC) whose parent is YUM! Brands, Inc. Franchisees operate a dine-in and carryout KFC outlet, which prepares and sells chicken and other approved menu items. The Franchise Agreement grants franchisees a license to use (i) certain KFC trademarks, trade names, service marks, logos and commercial symbols the franchisor periodically authorizes, including the “KFC” and “Kentucky Fried Chicken” marks; and (ii) the proprietary business formats, methods, procedures, designs, layouts, standards and specifications the franchisor authorizes, solely in connection with the operation of the outlet.</p>
<p><b>Training Overview:</b>Franchisees (or if they are an entity, the control person) must attend and complete, to the franchisor’s satisfaction, the initial training program offered by KFCLLC on the operation of an outlet. Franchisees may designate a key operator to complete the Key Operator Restaurant Training. At the franchisor’s direction, other employees of franchisees must attend and complete the training program to KFCLLC’s satisfaction. All training programs will be scheduled, as needed, at KFCLLC's designated national, regional or divisional offices or other places as the franchisor may designate. Training programs include computer-based training through its Learning Zone program, written material, on-the-job training at other outlets and classroom instruction. The individual who completes the Key Operator Restaurant Training will train employees at the outlet. The franchisor may require franchisees and their employees attend and complete additional and ongoing refresher training courses, programs and seminars at such times and locations that KFCLLC reasonably requires.</p>
<p><b>Territory Granted:</b> Franchisees will not receive an exclusive territory. However, so long as franchisees are in compliance with the Franchise Agreement, they will have a protected territory of the smaller of (i) a radius of 1.5 miles of the outlet, or (ii) an area around the outlet where 30,000 people reside, or, in the case of a metropolitan area containing more than 100,000 people, within which 30,000 people reside or work (the protected territory). The franchisee’s rights with respect to the protected territory will not be dependent upon achievement of a certain sales volume, market penetration or other performance factors. Within the protected territory, the franchisor will not use, or permit others to use in selling food products, any of the marks that franchisees have the right to use under the Franchise Agreement, except for (a) special event sales and (b) in some cases, food products (other than chicken in whole pieces) using the name or image of Colonel Sanders. Franchisees may only sell approved products at the outlet except for (i) catering and special event sales and (ii) delivery sales made only in accordance with KFCLLC’s catering and special events procedures and under a form it requires.</p>
<p><b>Obligations and Restrictions:</b> During the term of the Franchise Agreement, the franchisee or a fully-trained and qualified manager must devote full time to the management and operation of the outlet. If franchisees are a corporation, entity, partnership or have more than one owner, they must also designate a ‘Control Person,’ who is the individual with the authority to and actively direct the business affairs of a corporation or entity with respect to the outlet. Individual owners and individual owners’ spouses must also sign the Guaranty or Spousal Consent (as applicable) in their individual capacities. Franchisees must sell all required products as the franchisor periodically designates. Franchisees may not deliver any product from the outlet or anywhere. Franchisees may cater and make sales at special events, only if franchisees meet the franchisor’s catering and special event procedures; and in the case of catering and special event sales involving delivery, sign an addendum required by KFCLLC.</p>
<p><b>Term of Agreement and Renewal:</b> The length of the initial franchise term is 20 years. If they meet the requirements franchisees can renew, but may be asked to sign a contract with materially different terms and conditions than the original contract.</p>
<p><b>Financial Assistance:</b>YUM offers an optional lending assistance program for qualified minorities. The YUM Minority Assistance Program covers financing for new minority franchisees purchasing an existing outlet, purchasing an existing company-owned outlet, or developing a new outlet. YUM will guarantee 25% of the principal of the franchised business loan, up to a maximum of $3,000,000 per loan or franchisee. YUM can discontinue the YUM Minority Lending Assistance Program at any time. Except as described, KFCLCC does not offer, directly or indirectly, any arrangements for financing a franchisee’s initial investment or the continuing operation of the KFC business.</p>
</div>
<h1 style="font-size:20px;text-align:right; color:red;">Thanks & Regards</h1>
<p style="font-size:15;text-align:right;">Team KFC</p>
</div>
</div>
<?php include('footer.php'); ?>